# Content
headline: Überschrift
person: Stefanie Schutera
person_description: I'm blalala.
person_title: PhD Candidate in Mathematics
email: hellomyfriend@mailbox.org
twitter_username: sschutera
linkedin_username: stefanie-schutera
github_username: stefanieschutera

# Configuration
title: Stefanie Schutera
description: Resume Website Stefanie Schutera # It will appear in your document head meta (for Google search results) and in your feed.xml site description.
# baseurl: "" # optional subpath, e.g. /blog
# url: "http://stefanie.schutera.com/" # deployment
url: "localhost:3000" # local

exclude: ["package.json", "src", "node_modules", "vendor"]
