# Content
headline: Hi there, thanks for stopping by and feel free to reach out!
user_description: "These are my areas of interest:"
tech_a_headline: Tech
tech_a_content: I'm a mathematician who's trained in web dev, software engineering and data science.
tech_b_headline: Design
tech_b_content: I love to design anything - <br> spaces, furniture & of course UX.
tech_c_headline: Yoga
tech_c_content: Yoga improves my everyday life as a practice for mind, soul and body. <br> (RYT 200)
username: Stefanie Schutera
user_title: PhD Candidate in Mathematics
email: hellomyfriend@mailbox.org
twitter_username: sschutera
linkedin_username: stefanie-schutera
github_username: stefanieschutera

# Configuration
title: Stefanie Schutera
description: Resume Website Stefanie Schutera # It will appear in your document head meta (for Google search results) and in your feed.xml site description.
# baseurl: "" # optional subpath, e.g. /blog
url: "http://stefanie.schutera.com/" # deployment

exclude: ["package.json", "src", "node_modules", "vendor"]
